name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ./tracemap-frontend

jobs:
  build:
    name: building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run tsc
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./tracemap-frontend/build
  deploy:
    needs: [build]
    name: deploying to s3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./tracemap-frontend/build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::643625685022:role/terraformRestrictedAdmin
          aws-region: eu-central-1
      - name: upload build to s3
        run: aws s3 sync ./build/ s3://tracemap.eikemu.com/ --delete
      - name: invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id E3VLBU7WSF9N46 --paths '/*'