name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: building
    working-directory: ./tracemap-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm i
      - run: npm run tsc
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build
  deploy:
    needs: [build]
    name: deploying to web-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./frontend-build
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'
      - run: ssh-keyscan -H ${{ secrets.HETZNER_SERVER_IP }} >> ~/.ssh/known_hosts
      - run: scp -r ./frontend-build/* ${{ secrets.HETZNER_SERVER_USER }}@${{ secrets.HETZNER_SERVER_IP }}:/var/www/tracemap
    